# Generated by Django 5.0.1 on 2024-03-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dreams',
            new_name='Dream',
        ),
    ]
