# Generated by Django 5.0.1 on 2024-03-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_dreams_dream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='dream',
            new_name='dream_name',
        ),
    ]
