# Generated by Django 5.0.1 on 2024-03-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_dream_dream_dream_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(choices=[('colours', 'Colours'), ('relations', 'Relations'), ('churches', 'Churches'), ('cities', 'Cities'), ('subjects', 'Subjects'), ('vehicle', 'Vehicle'), ('food', 'Food'), ('fruits', 'Fruits'), ('animal', 'Animal'), ('places', 'Places'), ('activities', 'Activities'), ('things', 'Things')], max_length=100),
        ),
    ]
